version: 1.0.{build}
branches:
  only:
  - master
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore src\Splat.Contrib.sln
build:
  project: src\Splat.Contrib.sln
  verbosity: minimal
after_build:
- cmd: nuget pack src\Splat.Contrib\Splat.Contrib.nuspec -Symbols -NonInteractive -Version %APPVEYOR_BUILD_VERSION%
test:
  assemblies: src\Splat.Contrib.UnitTests\bin\Release\Splat.Contrib.UnitTests.dll
artifacts:
- path: src\Splat.Contrib\bin\Release\Splat.Contrib.*.nupkg
  name: nugetpackage
deploy:
- provider: NuGet
  api_key:
    secure: 8GpBZ6IHRM4AV4mP8qCqUgJi0NCHX17OlzbrEZRoDCE0s2ZwXHOeqMfIwrGaakg9
  on:
    APPVEYOR_REPO_BRANCH: Release
